version: '3.8'
services:
  centos7-init:
    image: anti1346/centos7:init
    restart: unless-stopped
    hostname: centos7
    container_name: centos7
    privileged: true
    user: root
    working_dir: /root/
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
