version: '3.8'

services:
  centos7-init:
    image: anti1346/centos7:init
    restart: unless-stopped
    hostname: centos7-init
    container_name: centos7-init
    privileged: true
    user: root
    working_dir: /root/
    command: /sbin/init
    volumes:
      - /run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - 2222:22


